node: Support for electron-rebuild
This allows the Desktop client to add this module as a dependency and
have its existing build process take care of building it against the
correct version of Electron. (Within the repo, `yarn build` calling
`electron-build-env` is still necessary; a plain `electron-rebuild`
seems to get confused.)

diff --git a/bin/build-node-bridge b/bin/build-node-bridge
--- a/bin/build-node-bridge
+++ b/bin/build-node-bridge
@@ -15,24 +15,21 @@ usage() {
 Usage: $(basename "$0") [-d] [-o DIR/]
 
 Options:
-	-d -- debug build (default is release)
-	-o -- where to copy the built module (default: node/dist/)
+	-d -- debug build (default is release, follows \$CONFIGURATION_NAME)
+	-o -- where to copy the built module (default: build/\$CONFIGURATION_NAME)
 END
 }
 
-CARGO_PROFILE_ARG=--release
-CARGO_PROFILE_DIR=release
-NODE_DIST_DIR=node/dist/
+CONFIGURATION_NAME=${CONFIGURATION_NAME:-Release}
 
 while [ "$1" != "" ]; do
   case $1 in
     -d | --debug )
-      CARGO_PROFILE_ARG=
-      CARGO_PROFILE_DIR=debug
+      CONFIGURATION_NAME=Debug
       ;;
     -o )
       shift
-      NODE_DIST_DIR="$1"
+      OUT_DIR="$1"
       ;;
     -h | --help )
       usage
@@ -45,15 +42,31 @@ while [ "$1" != "" ]; do
   shift
 done
 
+case ${CONFIGURATION_NAME} in
+  Debug )
+    CARGO_PROFILE_ARG=
+    CARGO_PROFILE_DIR=debug
+    ;;
+  Release )
+    CARGO_PROFILE_ARG=--release
+    CARGO_PROFILE_DIR=Release
+    ;;
+  * )
+    echo 'error: unexpected CONFIGURATION_NAME:' ${CONFIGURATION_NAME} >&2
+    exit 1
+esac
+
+OUT_DIR=${OUT_DIR:-build/${CONFIGURATION_NAME}}
+
 check_rust
 
-echo_then_run yarn electron-build-env cargo build -p libsignal-node ${CARGO_PROFILE_ARG}
+echo_then_run cargo build -p libsignal-node ${CARGO_PROFILE_ARG}
 
 for possible_library_name in libsignal_node.dylib libsignal_node.so signal_node.dll; do
-  possible_library_path="target/${CARGO_PROFILE_DIR}/${possible_library_name}"
+  possible_library_path="${CARGO_BUILD_TARGET_DIR:-target}/${CARGO_BUILD_TARGET}/${CARGO_PROFILE_DIR}/${possible_library_name}"
   if [ -e "${possible_library_path}" ]; then
-    echo_then_run mkdir -p "${NODE_DIST_DIR}"
-    echo_then_run cp "${possible_library_path}" "${NODE_DIST_DIR}"libsignal_client.node
+    echo_then_run mkdir -p "${OUT_DIR}"
+    echo_then_run cp "${possible_library_path}" "${OUT_DIR}"/libsignal_client.node
     break
   fi
 done
